### ISSUE TITLE
Segmentation fault when performing dump in latest version 

### ISSUE THREAD

**Issue by dabico** [databacker/mysql-backup#250]
This was originally observed in the discussion for #105. What follows are migrated excerpts from that discussion:

> `latest` won't do it. `latest` explicitly points at the most recent semver tag, i.e. not including `-beta*` or `-rc*` or any of that. You would need to use the explicit `1.0.0-rc1` tag.

_Originally posted by @deitch in https://github.com/databacker/mysql-backup/issues/105#issuecomment-1873917807_

> Okay got it, I thought `latest` pointed to that release. I updated the image and tried running with the config I posted above, but it only prints the `mysql-backup` description. Do I also have to specify a `command` in my compose config?

_Originally posted by @dabico in https://github.com/databacker/mysql-backup/issues/105#issuecomment-1873930188_

> Yeah, it only points to the most recent semver. Having it point to not-yet-released versions (beta or release candidates, etc.) would put out a version that is not ready. Like the current go-based one. Very close, but not there yet.

> > Do I also have to specify a `command` in my compose config?

> Yes. Took advantage of the major version release to clean up and make much more consistent CLI flags and env vars and names, and add a config file option.

```
$ mysql-backup
Backup or restore one or more mysql-compatible databases.
		In addition to the provided command-line flag options and environment variables,
		when using s3-storage, supports the standard AWS options:

		AWS_ACCESS_KEY_ID: AWS Key ID
		AWS_SECRET_ACCESS_KEY: AWS Secret Access Key
		AWS_REGION: Region in which the bucket resides

Usage:
  mysql-backup [command]

Available Commands:
  dump        backup a database
  help        Help about any command
  restore     restore a dump

Flags:
      --aws-access-key-id string       Access Key for s3 and s3 interoperable systems; ignored if not using s3.
      --aws-endpoint-url string        Specify an alternative endpoint for s3 interoperable systems e.g. Digitalocean; ignored if not using s3.
      --aws-region string              Region for s3 and s3 interoperable systems; ignored if not using s3.
      --aws-secret-access-key string   Secret Access Key for s3 and s3 interoperable systems; ignored if not using s3.
  -h, --help                           help for mysql-backup
      --pass string                    password for database server
      --port int                       port for database server (default 3306)
      --server string                  hostname for database server
      --smb-domain string              SMB domain
      --smb-pass string                SMB username
      --smb-user string                SMB username
      --tmp string                     temporary directory base for working directory, defaults to OS (default "/var/folders/7k/011x7ywd3ss305ntyxldy6mc0000gn/T/")
      --user string                    username for database server
  -v, --verbose int                    set log level, 1 is debug, 2 is trace
```

> Use "mysql-backup [command] --help" for more information about a command.

_Originally posted by @deitch in https://github.com/databacker/mysql-backup/issues/105#issuecomment-1873934988_

> After specifying the command I get the following error:

```log
2024-01-02T12:16:10.030319627Z time="2024-01-02T12:16:10Z" level=debug msg="starting dump"
2024-01-02T12:16:10.030480544Z time="2024-01-02T12:16:10Z" level=info msg="beginning dump 2024-01-02T12:16:10Z"
2024-01-02T12:16:10.033349259Z panic: runtime error: invalid memory address or nil pointer dereference
2024-01-02T12:16:10.033373050Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xad36e7]
2024-01-02T12:16:10.033376740Z 
2024-01-02T12:16:10.033379895Z goroutine 1 [running]:
2024-01-02T12:16:10.033382536Z github.com/databacker/mysql-backup/pkg/core.Dump({{0xc0001dcbc0, 0x1, 0x1}, 0x1, {0xc0001dcc50, 0x1, 0x1}, {{0x0, 0x0}, {0x0, ...}, ...}, ...})
2024-01-02T12:16:10.033385802Z 	/src/mysql-backup/pkg/core/dump.go:61 +0x1e7
2024-01-02T12:16:10.033388719Z github.com/databacker/mysql-backup/pkg/core.TimerDump({{0xc0001dcbc0, 0x1, 0x1}, 0x1, {0xc0001dcc50, 0x1, 0x1}, {{0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
2024-01-02T12:16:10.033391978Z 	/src/mysql-backup/pkg/core/dump.go:31 +0x13e
2024-01-02T12:16:10.033395016Z github.com/databacker/mysql-backup/cmd.dumpCmd.func2(0xc0000d3340?, {0xc659f8?, 0x8?, 0x8?})
2024-01-02T12:16:10.033397790Z 	/src/mysql-backup/cmd/dump.go:144 +0x7d7
2024-01-02T12:16:10.033400388Z github.com/spf13/cobra.(*Command).execute(0xc0000d3340, {0xc0000ada00, 0x8, 0x8})
2024-01-02T12:16:10.033403509Z 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x67c
2024-01-02T12:16:10.033406301Z github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d3080)
2024-01-02T12:16:10.033409451Z 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x39d
2024-01-02T12:16:10.033412621Z github.com/spf13/cobra.(*Command).Execute(...)
2024-01-02T12:16:10.033415643Z 	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
2024-01-02T12:16:10.033418367Z github.com/databacker/mysql-backup/cmd.Execute()
2024-01-02T12:16:10.033421320Z 	/src/mysql-backup/cmd/root.go:227 +0x68
2024-01-02T12:16:10.033424226Z main.main()
2024-01-02T12:16:10.033426621Z 	/src/mysql-backup/main.go:8 +0x17
```

> I only added a `dump` command to the existing configuration. Is some combination of the environment variables causing this? Do I need to also change those, either by renaming them or changing their values?

_Originally posted by @dabico in https://github.com/databacker/mysql-backup/issues/105#issuecomment-1873959063_

> Yes and no. Yes, (some of) the env vars have been renamed. No, it should not crash no matter what. Well, that is why it is a "release candidate" and not "generally available".

> Any way I can recreate that?

_Originally posted by @deitch in https://github.com/databacker/mysql-backup/issues/105#issuecomment-1873967197_

> Here's a repository with an MRE: https://github.com/dabico/mysql-backup-issue-105

_Originally posted by @dabico in https://github.com/databacker/mysql-backup/issues/105#issuecomment-1874134796_

**Comment by deitch** [comment]
For future reference, this is because `compressor` opt was nil, even though it shouldn't be. It shouldn't be, because `compressionVar := v.GetString("compression")` should never be blank, because it has default set.

The root cause is that we try to read the `compression` var in `root.cmd` from the root-level persistent flags, because it also can be in the config file, and that is where we read the config file, but read the `compression` var in the `dump` command, where it is a separate variable.
